### ISSUE TITLE
Oppdater ikonene

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdeltakere#14]

**Comment by AsgeirSH** [comment]
@mariusmandal Tror du det blir krise og at lokalkontaktene ikke finner igjen ting om jeg gjør dette i dag, eller er det kurant å få det likt med påmeldingssystemet så fort som mulig?

**Comment by AsgeirSH** [comment]
Eller bør det hele vente til vi tar hele greia?

**Comment by mariusmandal** [comment]
kjør på :)

**Comment by mariusmandal** [comment]
Kommer ny en
