### ISSUE TITLE
Enkeltperson-innslagtype beskrives med kode, ikke navn

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMdeltakere#44]
F.eks 
![image](https://user-images.githubusercontent.com/1831028/69501490-d15ce280-0f05-11ea-8326-8d174f4a78df.png)

Flerkamera, kamera => flerkamera_kamera

**Comment by mariusmandal** [comment]
Fixed by 8ff761b8a9c2d6aa55e03d3937967caf7a4f4713
