### ISSUE TITLE
Redigering av arrangører gjør at de mister rollen sin

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdeltakere#52]
Og det skal de jo ikke gjøre, stakkar

**Comment by mariusmandal** [comment]
Problemet er at ikke riktig checkbox krysses av når vi starter redigering

**Comment by AsgeirSH** [comment]
Denne er kinkigere enn forventa fordi vi bruker TwigJS, og kan dermed ikke kalle metodene vi har benyttet i Delta. Må skrive om litt mer enn jeg hadde tenkt, men har en plan og prøver å fikse den ila torsdag :)
