### ISSUE TITLE
Erfaringsfelt lagrer ikke

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMdeltakere#8]
Gjelder i alle fall nettredaksjonsinnlag (meldt fra Torstein, kan være at det kun gjelder festivalen)

**Comment by AsgeirSH** [comment]
Gjelder i hvert fall fylkesmønstringer, når man melder på direkte uten å videresendes.

**Comment by AsgeirSH** [comment]
```
{person: "133224", p_id: "133224", p_name: "Tester Taster", p_name_full: "Tester Taster",…}
advarsler: ""
b_id: "121060"
innslag: "Tester Taster"
instrument: ""
kategori: "Nettredaksjon"
p_alder: 25
p_email: "sad@fake.ukm.no"
p_id: "133224"
p_name: "Tester Taster"
p_name_full: "Tester Taster"
p_phone: "<span class="mobiltelefon">980 04 248</span>"
person: "133224"
personer: "1 person"
reload: false
sjanger: ""
snitt: 25
tittellos: true
```

Erfaringsfeltet blir ikke sendt med i ajax-requesten en gang.

**Comment by AsgeirSH** [comment]
Hmm, men det ser det ikke ut til at gjøres der det fungerer heller, i.e. kommunesiden. Dette krever mer etterforsking, usikker på hvorfor dette skjer.

**Comment by mariusmandal** [comment]
closed by https://github.com/UKMNorge/UKMdeltakere/commit/5f494930aadb112999e7f58f7e201428d8448589
